import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import '@/styles/globals.css'
import '@/styles/reset.css'
import type {Metadata} from 'next'
import Head from 'next/head'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ko">
      <Head>
        <link
          rel="stylesheet"
          as="style"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
        <script src="https://platform.instagram.com/en_US/embeds.js" async />
      </Head>
      <body>
        <div className="flex w-full flex-col">
          <Header />
          <div className="flex flex-col items-center pt-[60px] laptop:ml-[220px]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
