name: vercel 배포 (hellow public repo에 자동 push)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Ruby and Mustache
        run: |
          sudo apt-get install -y ruby-full
          gem install mustache

      - name: Generate Output
        run: sh ./build.sh

      - name: Push to kimfashion public repo
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v2
        env:
          API_TOKEN_GITHUB: ${{ secrets.OFFICIAL_ACCOUNT_GH_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: helloyukyung
          destination-repository-name: kimfashion-web
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
